[project]
name = "harri"
version = "0.1.0"
description = ""
authors = [
    {name = "Cedric McKeever",email = "cedricmckeever@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12,<4.0"
dependencies = [
    "pydantic-ai (>=1.82.0,<2.0.0)",
    "pandas (<3.0.0)",
    "pydantic (>=2.13.1,<3.0.0)",
    "jinja2 (>=3.1.6,<4.0.0)",
    "python-telegram-bot (>=22.7,<23.0)",
    "dotenv (>=0.9.9,<0.10.0)",
    "google-api-python-client (>=2.195.0,<3.0.0)",
    "google-auth-httplib2 (>=0.3.1,<0.4.0)",
    "google-auth-oauthlib (>=1.3.1,<2.0.0)",
]

[tool.poetry]
packages = [{include = "harri", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
cli = "harri.main:run_cli"
bot = "harri.main:run_telebot"

[dependency-groups]
optional = [
    "logfire (>=4.32.1,<5.0.0)",
    "colorlog (>=6.10.1,<7.0.0)"
]
dev = [
    "pytest (>=9.0.3,<10.0.0)",
    "pytest-xdist (>=3.8.0,<4.0.0)",
]

[tool.ruff]
line-length = 88
